# frozen_string_literal: true

module Meteoalarm
  COUNTRY_MAPPING = { 'AT' => 'austria',
                      'BA' => 'bosnia-herzegovina',
                      'BE' => 'belgium',
                      'BG' => 'bulgeria',
                      'CH' => 'switzerland',
                      'CY' => 'cyprus',
                      'CZ' => 'czechia',
                      'DE' => 'germany',
                      'DK' => 'denmark',
                      'EE' => 'estonia',
                      'ES' => 'spain',
                      'FI' => 'finland',
                      'FR' => 'france',
                      'GR' => 'greece',
                      'HR' => 'croatia',
                      'HU' => 'hungary',
                      'IE' => 'ireland',
                      'IL' => 'israel',
                      'IS' => 'iceland',
                      'IT' => 'italy',
                      'LT' => 'lithuania',
                      'LU' => 'luxembourg',
                      'LV' => 'latvia',
                      'MD' => 'moldova',
                      'ME' => 'montenegro',
                      'MK' => 'republic-of-north-macedonia',
                      'MT' => 'malta',
                      'NL' => 'netherlands',
                      'NO' => 'norway',
                      'PL' => 'poland',
                      'PT' => 'portugal',
                      'RO' => 'romania',
                      'RS' => 'serbia',
                      'SE' => 'sweden',
                      'SI' => 'slovenia',
                      'SK' => 'slovkia',
                      'UK' => 'united-kingdom' }.freeze
end